version: "3.5"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data: